---
apiVersion: v1 
kind: Service 
metadata: 
 name: result-app-service
 labels: 
  author: pooja
spec: 
 type: LoadBalancer
 selector: 
  name: result-app 
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30008